# Guess a prime number generated by the computer. 
# Prime number will be between 2 and 100.

# Start time: 6:57AM
# End time: 7:53AM

import sys, os, math, random
os.system("clear")

def isPrime(n):
    isPrime = True
    for i in range(2, n-1):
        if n % i == 0:
            isPrime = False
            break
    return isPrime

def generatePrimeNumbers(max):
    primes = []
    for i in range(2, max):
        isPrime = True
        for n in range(2, i-1):
            if i % n == 0:
                isPrime = False
                break
        if isPrime:
            primes.append(i)
    return primes

def getLowHotWarm(primes, n):
    idx_prime = primes.index(n)
    if (idx_prime - 2) >= 0:
        low_hot = primes[idx_prime - 2]
    else:
        low_hot = primes[0]
    if (idx_prime - 4) >= 0:
        low_warm = primes[idx_prime - 4]
    else:
        low_warm = primes[0]
    return low_warm, low_hot

def getHighHotWarm(primes, n):
    idx_prime = primes.index(n)
    max_range = len(primes) - 1
    if (idx_prime + 2) <= max_range:
        high_hot = primes[idx_prime + 2]
    else:
        high_hot = primes[max_range]
    if (idx_prime + 4) <= max_range:
        high_warm = primes[idx_prime + 4]
    else:
        high_warm = primes[max_range]
    return high_warm, high_hot

# -- main --
if len(sys.argv) >= 2:
    primeNumbers = generatePrimeNumbers(int(sys.argv[1]))
    r = random.randint(0, len(primeNumbers)-1)
    COMPUTER_PRIME_NUMBER = primeNumbers[r]
    LOW_WARM, LOW_HOT = getLowHotWarm(primeNumbers, COMPUTER_PRIME_NUMBER)
    HIGH_WARM, HIGH_HOT = getHighHotWarm(primeNumbers, COMPUTER_PRIME_NUMBER)

    gameComplete = False
    print(r)
    print(primeNumbers)
    print(COMPUTER_PRIME_NUMBER)
    print(LOW_WARM, LOW_HOT)
    print(HIGH_HOT, HIGH_WARM)
    while not gameComplete:
        userGuess = int(input("Guess a prime number between 1 and " + sys.argv[1] + ": "))
        if isPrime(userGuess):

            # Check bingo!
            if userGuess == COMPUTER_PRIME_NUMBER:
                print("Winner, winner. Chicken dinner! You got it!!")
                gameComplete = True
                break
            
            # Check lows
            if userGuess >= LOW_HOT and userGuess < COMPUTER_PRIME_NUMBER:
                message = "You guessed low, but are very close. Definitely Hot!"
            elif userGuess >= LOW_WARM and userGuess < LOW_HOT:
                message = "You guessed low, but could do better. I feel Warm!"
            elif userGuess < LOW_WARM:
                message = "Wow! too far..."
            
            # Check highs
            if userGuess <= HIGH_HOT and userGuess > COMPUTER_PRIME_NUMBER:
                message = "You guessed high, but are very close. Definitely Hot!"
            elif userGuess <= HIGH_WARM and userGuess > HIGH_HOT:
                message = "You guessed high, but could do better. I feel Warm!"
            elif userGuess > HIGH_WARM:
                message = "Wow! not even close..."

            print("\n" + message + "\n")

        else:
            print("That is not a prime number.")
else:
    print("\nIncorrect usage. \nCorrect usage: python3 " + sys.argv[0] + " NN")
